[package]
name = "ligature"
version = "0.1.0"
authors = ["Alex Michael Berry <berry3@indiana.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
